### ISSUE TITLE
README is wrong!

### ISSUE THREAD

**Issue by topcoderkz** [omrikiei/aws_logging_handlers#10]
Please change 
from aws_logging_handlers import S3Handler --> from aws_logging_handlers.S3 import S3Handler

from aws_logging_handlers import KinesisHandler --> from aws_logging_handlers.Kinesis import KinesisHandler

Also, even though it uploads logs to S3 bucket,  the whole program (in readme) hangs!

**Comment by omrikiei** [comment]
Hi, README is fixed, I'll try to take a look at the README code that hangs sometime soon. Thank you for bringing it to my attention - I indeed did not update the readme code following the refactoring I've done
