### ISSUE TITLE
S3Handler blocks Python from exiting

### ISSUE THREAD

**Issue by mattilyra** [omrikiei/aws_logging_handlers#11]
Using this handler prevents python from exiting - tested on `3.7.3` and `3.6.8`

This could be caused by the teardown signal handler for the S3 logging handler, which is wrong. The documentation says that the signal handlers take 2 arguments

> The handler is called with two arguments: the signal number and the current stack frame (None or a frame object; for a description of frame objects, see the description in the type hierarchy or see the attribute descriptions in the inspect module).

the `_teardown` function takes a single arg.

I tried fixing that locally but the exit still hangs.

Closing the log handler explicitly before `exit` solves the issue but this really shouldn't be necessary.

Hitting `ctrl+c` once the program is frozen gives the following traceback

```Exception ignored in: <module 'threading' from '/usr/local/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/local/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt```

**Comment by omrikiei** [comment]
@mattilyra you brought up a good point.
This is caused because the handlers manage worker threads that do the actual streaming work and they communicate using queues. when the main thread finished executing it hangs because the worker threads are programmed to 'run forever' and they are not daemon threads, I've changed them to daemon threads - it's currently in the source and after testing it more throughly I'll release it in a minor version.

**Comment by omrikiei** [comment]
ok, tested, and will release a minor version with a fix

**Comment by omrikiei** [comment]
and additionally, I've fixed the signal handler function signatures - great catch

**Comment by amsoell** [comment]
Came here looking for a solution to this problem, [release 2.0.3](/omrikiei/aws_logging_handlers/releases/tag/v2.0.3) seems to fix things for me. Thanks for getting that implemented, @omrikiei !
