### ISSUE TITLE
Possible issue with strftime(%s) etc.

### ISSUE THREAD

**Issue by tuukkasarvi** [omrikiei/aws_logging_handlers#13]
Hello and thanks for the package. I get an error when I run the example code in README.
I am using Python 3.6.7.

import logging
from aws_logging_handlers.S3 import S3Handler

bucket="test_bucket" # The bucket should already exist
s3_handler = S3Handler("test_log", bucket)

I get:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\username\python_venvs\env_name\lib\site-packages\aws_logging_handlers\S3\__init__.py", line 331, in __init__
    compress=compress, **boto_session_kwargs)
  File "C:\Users\username\python_venvs\env_name\lib\site-packages\aws_logging_handlers\S3\__init__.py", line 98, in __init__
    self.start_time = int(datetime.utcnow().strftime('%s'))
ValueError: Invalid format string

I tried to replace strftime('%s') timestamp() , see:
https://stackoverflow.com/questions/11743019/convert-python-datetime-to-epoch-with-strftime

But then I got another error:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\username\python_venvs\env_name\lib\site-packages\aws_logging_handlers\S3\__init__.py", line 336, in __init__
    signal.signal(signal.SIGQUIT, self._teardown)
AttributeError: module 'signal' has no attribute 'SIGQUIT'

**Comment by omrikiei** [comment]
Hi, it seems that this issue derives from a runtime environment difference.. which OS and kernel are you using?

**Comment by carlosmontoya89** [comment]
@omrikiei @tuukkasarvi this is an issue Python doesn't actually support %s as an argument to strftime (if you check at http://docs.python.org/library/datetime.html#strftime-and-strptime-behavior it's not in the list), the only reason it's working is because Python is passing the information to your system's strftime, which uses your local timezone.

I am using windows and it does not work, like @tuukkasarvi  i tried modifing the stfrtime but then i got another error.

the library looked really good but it cant be used

**Comment by tuukkasarvi** [comment]
Hi, sorry for late reply and thanks for the comments. I am using windows 10. This is not a pressing issue for me as we implemented other means of logging but I am glad if I can help

**Comment by Fizpok** [comment]
Hi, @omrikiei, please fix this issue, parameter %s in strftime() isn't a valid parameter according to Python standard: [](http://docs.python.org/library/datetime.html#strftime-and-strptime-behavior)
Thanks.

**Comment by omrikiei** [comment]
@Fizpok can you please fork+PR? It might take me a while to address this..

**Comment by Fizpok** [comment]
> @Fizpok can you please fork+PR? It might take me a while to address this..

Ok, but what you mean on line 337 in `__init__.py`? 

I got an error:
```
 Connected to pydev debugger (build 201.7223.92)
Traceback (most recent call last):
  File "C:/Git/dataresearch/as_interface/main_send_as.py", line 117, in main_run
    host, oauth_client_id, oauth_client_secret = init()
  File "C:/Git/dataresearch/as_interface/main_send_as.py", line 51, in init
    s3_handler = S3Handler("test_log.txt", log_bucket, aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key)
  File "C:\Git\dataresearch\as_interface\venv\lib\site-packages\aws_logging_handlers\S3\__init__.py", line 337, in __init__
    signal.signal(signal.SIGQUIT, self._teardown)
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```
According to [https://docs.python.org/3/library/signal.html](https://docs.python.org/3/library/signal.html)  signal.SIGQUIT is wrong constant.

Thanks.

**Comment by omrikiei** [comment]
SIGQUIT is only available in unix systems, I think it can be remove from the signal handlers...

**Comment by Fizpok** [comment]
Remove only in non-Windows systems?

My dev env is Win, but prod - Linux.

P.S. Shana tova ahi :)

пн, 21 сент. 2020 г., 20:43 Omri Eival <notifications@github.com>:

**Comment by omrikiei** [comment]
I think you can remove it altogether, either that or check that signal has the SIGQUIT attr..

Shana tova :)
