### ISSUE TITLE
Logs go to S3 only after handler shutdown

### ISSUE THREAD

**Issue by fegoulart** [omrikiei/aws_logging_handlers#17]
I cannot see my logs before handler shutdown

**Comment by bartekchowaniec** [comment]
> I cannot see my logs before handler shutdown
@fegoulart - Did You solve that problem somehow? I think I have a similar problem - I can see only one log on s3...

**Comment by fegoulart** [comment]
I guess S3 files cannot append text, so they are uploaded only when the
size or time limit is reached.

Em ter, 24 de mar de 2020 08:01, bartekchowaniec <notifications@github.com>
escreveu:

**Comment by omrikiei** [comment]
@fegoulart is correct, what you can do is configure a very short buffer/interval

**Comment by bartekchowaniec** [comment]
@fegoulart, @omirikiei - Thank You, guys.

**Comment by omrikiei** [comment]
check out  `max_file_log_time` and `max_file_size_bytes`
